In [1]:
import torch

In [2]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [3]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [4]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [5]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [6]:
X>Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [14]:
a = torch.arange(9).reshape((3, 3,1))
b = torch.arange(6).reshape((1, 1,6))
a, b

(tensor([[[0],
          [1],
          [2]],
 
         [[3],
          [4],
          [5]],
 
         [[6],
          [7],
          [8]]]),
 tensor([[[0, 1, 2, 3, 4, 5]]]))

In [15]:
a+b

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 1,  2,  3,  4,  5,  6],
         [ 2,  3,  4,  5,  6,  7]],

        [[ 3,  4,  5,  6,  7,  8],
         [ 4,  5,  6,  7,  8,  9],
         [ 5,  6,  7,  8,  9, 10]],

        [[ 6,  7,  8,  9, 10, 11],
         [ 7,  8,  9, 10, 11, 12],
         [ 8,  9, 10, 11, 12, 13]]])